
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"

brew "helix"
brew "exa"
brew "bat"
brew "starship"
brew "git"
brew "zsh-syntax-highlighting"
brew "zsh-autosuggestions"

cask "iterm2"
cask "brave-browser"
cask "visual-studio-code"
cask "spotify"
cask "font-jetbrains-mono"
cask "font-jetbrains-mono-nerd-font"